spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whatsapp?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
password:
  secret-key: secretpassword1234mustbeatleast128bitslalalalalala
server:
  port: 8081
